return {
  -- "nvim-java/nvim-java",
  -- lazy = true,
  -- opts = {},
  -- specs = {
  --   "nvim-java/lua-async-await",
  --   "nvim-java/nvim-java-core",
  --   "nvim-java/nvim-java-test",
  --   "nvim-java/nvim-java-dap",
  --   "MunifTanjim/nui.nvim",
  --   "neovim/nvim-lspconfig",
  --   {
  --     "williamboman/mason.nvim",
  --     opts = {
  --       registries = {
  --         "github:nvim-java/mason-registry",
  --         "github:mason-org/mason-registry",
  --       },
  --     },
  --   },
  --   { "mfussenegger/nvim-jdtls", optional = true, enabled = true },
  --   {
  --     "AstroNvim/astrolsp",
  --     optional = true,
  --     ---@type AstroLSPOpts
  --     opts = {
  --       servers = { "jdtls" },
  --       handlers = {
  --         jdtls = function(server, opts)
  --           require("lazy").load { plugins = { "nvim-java" } }
  --           require("lspconfig")[server].setup(opts)
  --         end,
  --       },
  --     },
  --   },
  -- },
}
