// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "495dbb66-b74e-49f6-8650-047f0efe050c");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1772808198);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1772808197);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "3ddaffa0-d74a-49e5-90f6-7127cf83abac");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1772808191);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1772808189);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 163);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v4:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.impressionId", "{1aa0b36f-f89b-44aa-9e40-3b52566d95db}");
user_pref("browser.newtabpage.disableNewTabAsAddon", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "149.2.20260220.204414");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.profiles.enabled", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1772808197813");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1772829797813");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260223201419");
user_pref("browser.startup.homepage_override.mstone", "148.0");
user_pref("browser.startup.lastColdStartupCheck", 1772808191);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 6);
user_pref("captchadetection.lastSubmission", 1772808);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "8cd68e4d-832f-44b4-a755-d4088de5857c");
user_pref("datareporting.dau.cachedUsageProfileID", "d341a10a-0e1a-4436-9a0c-452c5fae0da4");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1772808191378");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "148.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "e59f441518c54e8dbccb7e0dd365d61d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260223201419");
user_pref("extensions.lastAppVersion", "148.0");
user_pref("extensions.lastPlatformVersion", "148.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_interventions", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"282c1cd8-0e22-4166-8ea4-0f2b99e5d66a\",\"formautofill@mozilla.org\":\"219403fc-54ab-4617-92d1-db20206c5871\",\"ipp-activator@mozilla.com\":\"8beadb1c-4f46-4bf4-9a95-15706034baf1\",\"pictureinpicture@mozilla.org\":\"64f2fbc1-9d60-4a2a-8c78-def0abf1b88e\",\"addons-search-detection@mozilla.com\":\"3e5b0e83-4249-464a-9961-8759b495b21b\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"72b0767b-33aa-464e-bca5-127b2e4caaa9\",\"default-theme@mozilla.org\":\"13c64f6e-da4d-485d-80ac-89afaa797cec\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "84379639-03bd-43d8-9a00-79f22bf38352");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("toolkit.profiles.storeID", "57d908a9");
user_pref("toolkit.startup.last_success", 1772808189);
user_pref("toolkit.telemetry.cachedClientID", "32678e24-d5af-474a-acdb-dce0fa2a5c58");
user_pref("toolkit.telemetry.cachedProfileGroupID", "614cd48d-d708-429b-8f9b-1bbca6a46aed");
user_pref("toolkit.telemetry.previousBuildID", "20260223201419");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
