# ~/.config/hypr/hyprland.conf

$waybarscripts = ~/.config/waybar/scripts
$mod = Super
$terminal = kitty

# Launch CLI
bind = $mod, B, exec, $terminal -e $waybarscripts/bluetooth
bind = $mod, N, exec, $terminal -e $waybarscripts/network
bind = $mod, O, exec, $terminal -e $waybarscripts/power
bind = $mod, U, exec, $terminal -e $waybarscripts/update

# Toggle off Bluetooth/Wi-Fi
bind = $mod Alt, B, exec, $scripts/bluetooth off
bind = $mod Alt, N, exec, $scripts/network off

# Refresh `custom/update` module
bind = $mod Alt, U, exec, pkill -RTMIN+1 waybar

# Adjust volume
bindl = , XF86AudioMicMute, exec, $scripts/volume input mute
bindl = , XF86AudioMute, exec, $scripts/volume output mute
bindel = , XF86AudioLowerVolume, exec, $scripts/volume output lower
bindel = , XF86AudioRaiseVolume, exec, $scripts/volume output raise

# Adjust brightness
bindel = , XF86MonBrightnessDown, exec, $scripts/backlight down
bindel = , XF86MonBrightnessUp, exec, $scripts/backlight up
